[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=44BEFC7C41A37648A945CC90242EA3E3
bStartInVR=True

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Shipping
BuildTarget=
FullRebuild=False
ForDistribution=True
IncludeDebugFiles=False
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bUseIoStore=False
bUseZenStore=False
bMakeBinaryConfig=False
bGenerateChunks=True
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=True
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
WriteBackMetadataToAssetRegistry=Disabled
bCompressed=True
PackageCompressionFormat=Oodle
bForceUseProjectCompressionFormatIgnoreHardwareOverride=False
PackageAdditionalCompressionOptions=
PackageCompressionMethod=Kraken
PackageCompressionLevel_DebugDevelopment=4
PackageCompressionLevel_TestShipping=5
PackageCompressionLevel_Distribution=7
PackageCompressionMinBytesSaved=1024
PackageCompressionMinPercentSaved=5
bPackageCompressionEnableDDC=False
PackageCompressionMinSizeToConsiderDDC=0
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=True
bDeterministicShaderCodeOrder=False
bSharedMaterialNativeLibraries=True
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=False
InternationalizationPreset=English
-CulturesToStage=en
+CulturesToStage=en
LocalizationTargetCatchAllChunkId=0
bCookAll=False
bCookMapsOnly=True
bSkipEditorContent=False
bSkipMovies=True
-IniKeyDenylist=KeyStorePassword
-IniKeyDenylist=KeyPassword
-IniKeyDenylist=rsa.privateexp
-IniKeyDenylist=rsa.modulus
-IniKeyDenylist=rsa.publicexp
-IniKeyDenylist=aes.key
-IniKeyDenylist=SigningPublicExponent
-IniKeyDenylist=SigningModulus
-IniKeyDenylist=SigningPrivateExponent
-IniKeyDenylist=EncryptionKey
-IniKeyDenylist=DevCenterUsername
-IniKeyDenylist=DevCenterPassword
-IniKeyDenylist=IOSTeamID
-IniKeyDenylist=SigningCertificate
-IniKeyDenylist=MobileProvision
-IniKeyDenylist=IniKeyDenylist
-IniKeyDenylist=IniSectionDenylist
+IniKeyDenylist=KeyStorePassword
+IniKeyDenylist=KeyPassword
+IniKeyDenylist=rsa.privateexp
+IniKeyDenylist=rsa.modulus
+IniKeyDenylist=rsa.publicexp
+IniKeyDenylist=aes.key
+IniKeyDenylist=SigningPublicExponent
+IniKeyDenylist=SigningModulus
+IniKeyDenylist=SigningPrivateExponent
+IniKeyDenylist=EncryptionKey
+IniKeyDenylist=DevCenterUsername
+IniKeyDenylist=DevCenterPassword
+IniKeyDenylist=IOSTeamID
+IniKeyDenylist=SigningCertificate
+IniKeyDenylist=MobileProvision
+IniKeyDenylist=IniKeyDenylist
+IniKeyDenylist=IniSectionDenylist
-IniSectionDenylist=HordeStorageServers
-IniSectionDenylist=StorageServers
+IniSectionDenylist=HordeStorageServers
+IniSectionDenylist=StorageServers
+MapsToCook=(FilePath="/Game/Maps/Movie")
+DirectoriesToAlwaysStageAsUFS=(Path="Movies")

[/Script/Plugins.ChunkDownloader VRVideoLive]
+CdnBaseUrls="http://192.168.2.111:8080"

[VRWebSocket]
bAutoConnectOnInit=True

ServerURL="ws://10.10.10.252:12899/websocket"
DeviceIdOverride=

ClientType=1
bUseSignedHandshake=True
SignaturePrefix="fD1$W6jP"
SignatureSuffix="G7p2Z#wX"

UploadIntervalSeconds=1.0
QuitDelaySeconds=2

[VRRemoteConfig]

; 这里必须填写电脑的局域网IP，不能写127.0.0.1
ConfigURL="http://192.168.2.111:8080/vr_config.json"

RequestTimeoutSeconds=5.0
bEnableRemoteConfig=True

[VRChunk]
; 同时作为本地兜底地址。必须包含Build文件夹名。
PakBuildUrl="http://10.10.10.252:8080/files/203e003c8c1ed48da66cf0a29fed97e3/v1.2.0"
+ChunkIds=1001
+ChunkIds=1002
+ChunkIds=1003
+ChunkIds=1004
+ChunkIds=1005
+ChunkIds=1006
+ChunkIds=1007
+ChunkIds=1008
+ChunkIds=1009
+ChunkIds=1010
+ChunkIds=1011
+ChunkIds=1012
+ChunkIds=1013
+ChunkIds=1014
+ChunkIds=1015
+ChunkIds=1016
TargetDownloadsInFlight=1
TargetDownloadsInFlight=1
DownloadPriority=1

[VRMedia]
+VideoDurations=10.000
+VideoDurations=131.967
+VideoDurations=260.133
+VideoDurations=158.267
+VideoDurations=61.367
+VideoDurations=34.133
+VideoDurations=63.600
+VideoDurations=155.100
+VideoDurations=85.600
+VideoDurations=72.333
+VideoDurations=89.867
+VideoDurations=116.667
+VideoDurations=214.967
+VideoDurations=194.767
+VideoDurations=92.300
+VideoDurations=138.067

