[Chunk1001Movies]
;只有用了 Generate Chunks 才会使用以下规则
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1001"
+Files=".../0_GuidSpace.mp4"

[Chunk1002Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1002"
+Files=".../1_SeqUniverse_8k_1.mp4"

[Chunk1003Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1003"
+Files=".../2_SeqZhuJian_8k.mp4"

[Chunk1004Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1004"
+Files=".../3_SeqJZ_8K_1.mp4"

[Chunk1005Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1005"
+Files=".../4_SeqHLD_8k.mp4"

[Chunk1006Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1006"
+Files=".../5_SeqYWJ_8k.mp4"

[Chunk1007Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1007"
+Files=".../6_SeqXM_8k.mp4"

[Chunk1008Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1008"
+Files=".../7_SeqYWXJ_8k.mp4"

[Chunk1009Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1009"
+Files=".../8_seqSZC_8k.mp4"

[Chunk1010Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1010"
+Files=".../9_SeqDZC_8k.mp4"

[Chunk1011Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1011"
+Files=".../10_SeqHBKJ_8k.mp4"

[Chunk1012Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1012"
+Files=".../11_SeqXueLangdao_8k.mp4"

[Chunk1013Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1013"
+Files=".../12_SeqZWGN_8k.mp4"

[Chunk1014Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1014"
+Files=".../13_SeqQTKJ_8k.mp4"

[Chunk1015Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1015"
+Files=".../15_SeqMJYZ_8k.mp4"

[Chunk1016Movies]
bOnlyChunkedBuilds=true
bOverrideChunkManifest=true
OverridePaks="pakchunk1016"
+Files=".../Sc16_FYHB_8K.mp4"